### ISSUE TITLE
一个jpa的问题

### ISSUE THREAD

**Issue by bfyxzls** [cooper-lyt/keycloak-phone-provider#13]
您好，我再部署时，把咱们的phone-provider打到docker里之后，在启动容器时出现这个问题，jpa的，感觉是keycloak里的jpa没有被我们引用上。
```
10:06:53,598 WARN  [org.jboss.modules.define] (ServerService Thread Pool -- 60) Failed to define class org.keycloak.phone.providers.jpa.TokenCodeJpaEntityProviderFactory in Module "keycloak-phone-provider" from local module loader @45312be2 (finder: local module finder @7fb95505 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base)): java.lang.NoClassDefFoundError: Failed to link org/keycloak/phone/providers/jpa/TokenCodeJpaEntityProviderFactory (Module "keycloak-phone-provider" from local module loader @45312be2 (finder: local module finder @7fb95505 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base))): org/keycloak/connections/jpa/entityprovider/JpaEntityProviderFactory
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
        at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
        at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
        at org.jboss.modules.Module.loadModuleClass(Module.java:731)
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1209)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at org.keycloak.keycloak-services@11.0.3//org.keycloak.provider.DefaultProviderLoader.load(DefaultProviderLoader.java:60)

```

**Comment by cooper-lyt** [comment]
不是jpa的问题， 这是找不到spi注册的jar包。

**Comment by bfyxzls** [comment]
@cooper-lyt 是我的问题，我把model-jpa模块不小心删除了，对了，咱们这个项目实现了手机号登陆的表单吗？我把theme设置成了phone，但登陆时没有效果

**Comment by cooper-lyt** [comment]
暂无电话号直接登录，仅有短信 OPT
