### ISSUE TITLE
Problems installing it on Keycloak(12.0.2)

### ISSUE THREAD

**Issue by SalahAdDin** [cooper-lyt/keycloak-phone-provider#14]
Thanks for this great work, it helps us to provide phone authentication to our users and it is very cool.

I found a mismatch on the documentation:
`<provider>module:keycloak-sms-provider</provider>` should be `<provider>module:keycloak-phone-provider</provider>`, isn't it?

```bash
17:58:55,206 INFO [org.keycloak.services] (ServerService Thread Pool -- 64) KC-SERVICES0001: Loading config from standalone.xml or domain.xml

17:58:55,261 FATAL [org.keycloak.services] (ServerService Thread Pool -- 64) Error during startup: java.lang.RuntimeException: org.jboss.modules.ModuleNotFoundException: keycloak-sms-provider
```

Fixing this in my installation file i got the next issue:
```bash
18:08:28,688 INFO [org.keycloak.services] (ServerService Thread Pool -- 71) KC-SERVICES0001: Loading config from standalone.xml or domain.xml

18:08:28,736 FATAL [org.keycloak.services] (ServerService Thread Pool -- 71) Error during startup: java.lang.RuntimeException: org.jboss.modules.ModuleNotFoundException: keycloak-phone-provider

at org.keycloak.keycloak-wildfly-extensions@12.0.2//org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:45)

at org.keycloak.keycloak-services@12.0.2//org.keycloak.provider.ProviderManager.<init>(ProviderManager.java:65)

at org.keycloak.keycloak-services@12.0.2//org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:90)

at org.keycloak.keycloak-services@12.0.2//org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:260)

at org.keycloak.keycloak-services@12.0.2//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:125)

at org.keycloak.keycloak-wildfly-extensions@12.0.2//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:29)

at org.keycloak.keycloak-services@12.0.2//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:115)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2815)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:371)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:283)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:93)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:140)

at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:305)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)

at io.undertow.servlet@2.2.2.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:97)

at org.wildfly.extension.undertow@21.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)

at java.base/java.lang.Thread.run(Thread.java:834)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

Caused by: org.jboss.modules.ModuleNotFoundException: keycloak-phone-provider

at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:297)

at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:283)

at org.keycloak.keycloak-wildfly-extensions@12.0.2//org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:41)

... 42 more
```

No idea what it is about.

My **Dockerfile**:
```Dockerfile
FROM jboss/keycloak:12.0.2

WORKDIR '/opt/jboss/keycloak/themes'

RUN curl -L -O https://github.com/cooper-lyt/keycloak-phone-provider/archive/master.tar.gz && tar -zxvf master.tar.gz && rm master.tar.gz
RUN mv keycloak-phone-provider-master/keycloak-phone-provider ${JBOSS_HOME}/modules/
RUN mv keycloak-phone-provider-master/keycloak-sms-provider-dummy ${JBOSS_HOME}/modules/
RUN rm -rf keycloak-phone-provider-master

# RUN curl https://github.com/simon-feamzy/keycloak-apple-social-identity-provider/releases/download/v1.0.4/apple-social-identity-provider-1.0.4.jar -o apple-social-identity-provider-1.0.4.jar
# RUN ${JBOSS_HOME}/bin/jboss-cli.sh --command="module add --name=fr.benjaminfavre.provider --resources=apple-social-identity-provider-1.0.4.jar --dependencies=org.keycloak.keycloak-core,org.keycloak.keycloak-services,org.keycloak.keycloak-server-spi,org.keycloak.keycloak-server-spi-private"
COPY ./standalone/configuration/standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml

RUN mkdir macondo
RUN cp -R ./keycloak/* macondo
COPY ./themes/login/. ./macondo/login
```

What could it be the problem?

Have you thinking about create _ear_ files for this providers? It could make it easy to install them in the _JBoss/Keycloak_ image since[ it get all needed providers](https://stackoverflow.com/questions/57208709/keycloak-spi-providers-and-layers-not-loading-when-using-docker/57210879#57210879) from `standalone/deployments` folder. 

Tested on  _JBoss/Keycloak_`11.0.3`:
```bash
18:29:17,010 INFO [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 536ms

18:29:17,043 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "microprofile-metrics-smallrye")]): java.lang.NullPointerException

at org.wildfly.extension.microprofile.metrics-smallrye@20.0.1.Final//org.wildfly.extension.microprofile.metrics.MicroProfileMetricsSubsystemAdd$2.execute(MicroProfileMetricsSubsystemAdd.java:86)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:999)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:743)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:467)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1413)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:527)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:515)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:477)

at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:451)

at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:404)

at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)

at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cooper-lyt** [comment]
1. you are right! but use docker build is not need this!
2. this is jar not found. " standalone/deployments  " is Wrong directory , you can use my  [ jboss-cli script ](https://github.com/cooper-lyt/keycloak-phone-provider/blob/master/jboss-cli/module-add.cli).
3.  Refer my [Dockerfile](https://github.com/cooper-lyt/keycloak-phone-provider/blob/master/docker/Dockerfile)
4. Please check your configuration,  These errors appear to have nothing to do with this project

**Comment by SalahAdDin** [comment]
@cooper-lyt I'm trying to understand something: if there is not _jar_ files, how does the `jboss-cli script` setup the modules?

i'm knew working with **Keycloak**.

**Comment by cooper-lyt** [comment]
`module add --name=cloopen-sms-sdk --resources=java-sms-sdk-1.0.3.jar --dependencies=javax.xml.bind.api,com.google.code.gson,org.dom4j,org.apache.httpcomponents,org.apache.commons.codec,org.apache.commons.logging
module add --name=keycloak-sms-provider-cloopen --resources=keycloak-sms-provider-cloopen.jar --dependencies=org.keycloak.keycloak-core,org.keycloak.keycloak-server-spi,org.jboss.logging,keycloak-phone-provider,cloopen-sms-sdk
`

in my script,  put jar to script same directory .

**Comment by SalahAdDin** [comment]
where can we get the `jar` file for every provider?

**Comment by cooper-lyt** [comment]
Refer my Dockerfile

**Comment by SalahAdDin** [comment]
I think there is a misunderstand here: to make the provider's installing easier it would be better if you provide the `jar` or `ear` file from every provider you made here.

**Comment by SalahAdDin** [comment]
I think there is a misunderstand here: to make the provider's installing easier it would be better if you provide the `jar` or `ear` file from every provider you made here.

@cooper-lyt They are included in your **Dockerfile** by the way, they seem to be included on your _coopersoft/keycloak-callback image:
```Dockerfile
#totalvoice provider
COPY modules/keycloak-sms-provider-totalvoice/main/keycloak-sms-provider-totalvoice.jar .
```

**Comment by cooper-lyt** [comment]
now support Quarkus keycload 19.0.1 , check readme.
